fix(selectListItem): fix selected list item
BlueBaseJS/plugin-react-native-paper pull request #384
Opened 2021-02-22 12:32 UTC by zubaria1

## Description
fix selected list item on mobile

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-02-26 09:45 UTC, AijazBlueeast approved these changes
in react native paper there isn't any selected prop so we pass the selected prop and give the list colour on light and dark mode

2021-03-01 06:11 UTC, artalat requested changes

2021-03-01 06:11 UTC, artalat commented on src/components/ListItem/ListItem.tsx
> +			backgroundColor: theme.theme.mode === 'dark' ? '#686868' : '#dbdbdb',
@AijazBlueeast please discuss with me

2021-03-03 10:58 UTC, artalat approved these changes

2021-03-03 10:58 UTC, merged

2021-10-31 10:32 UTC, artalat commented
:tada: This PR is included in version 4.0.0-beta.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@bluebase/plugin-react-native-paper)
- [GitHub release](https://github.com/BlueBaseJS/plugin-react-native-paper/releases/tag/v4.0.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-07-19 18:11 UTC, artalat commented
:tada: This PR is included in version 4.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@bluebase/plugin-react-native-paper)
- [GitHub release](https://github.com/BlueBaseJS/plugin-react-native-paper/releases/tag/v4.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: